language: go
go:
- 1.6
- 1.7
- 1.8
- tip

before_install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install
  && cd -
- go get github.com/mattn/goveralls

install:
- make install

script:
- make test

after_success:
- "$HOME/gopath/bin/goveralls -service=travis-ci"

